version: "2.4"

services:
  mysql:
    container_name: mysql_host
    image: mysql/mysql-server:5.6
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_ROOT_HOST: "%"
    ports:
    - 3306:3306
